baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Geliiil'
theme = "lun-theme"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20

  [[menu.main]]
    identifier = "collections"
    name = "Collections"
    url = "/collections"
    weight = 30

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 40

  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/Geliiil"
  weight = 1
  [menu.social.params]
      icon = "icon/GitHub_Logo.svg" 
      newTab = true

[params.profile]
avatar = "/image/IMG_5888.jpg"
name ="Geliiil"
description = "Hello, 我是Geliiil"


[taxonomies]
tag = "tags"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1