baseURL = "https://example.com"
title = "Hugo template"
themes = "lun-theme"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20

[params]
  avatar = "assets/IMG_5888.jpg"